# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Jeremie/Dropbox/Master/Cours/Semestre2/LPSC/Labo/Labo/mse_mandelbrot_no_bram/mse_mandelbrot.srcs/sources_1/ip/ram_dual_port/ram_dual_port.xci
# IP: The module: 'ram_dual_port' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jeremie/Dropbox/Master/Cours/Semestre2/LPSC/Labo/Labo/mse_mandelbrot_no_bram/mse_mandelbrot.srcs/sources_1/ip/ram_dual_port/ram_dual_port_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_dual_port'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Jeremie/Dropbox/Master/Cours/Semestre2/LPSC/Labo/Labo/mse_mandelbrot_no_bram/mse_mandelbrot.srcs/sources_1/ip/ram_dual_port/ram_dual_port.xci
# IP: The module: 'ram_dual_port' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jeremie/Dropbox/Master/Cours/Semestre2/LPSC/Labo/Labo/mse_mandelbrot_no_bram/mse_mandelbrot.srcs/sources_1/ip/ram_dual_port/ram_dual_port_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_dual_port'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
